### ISSUE TITLE
Lab 06: Dorling cartogram?

### ISSUE THREAD

**Issue by mtwelker** [Watts-College/cpp-527-fall-2021#45]
Prof. Lecy,
I don't remember doing a Dorling cartogram in my CPP 526 class.  Can you provide a link to this assignment so I can better understand what the purpose was?
Thank you!

**Comment by Rami-Assaad** [comment]
@mtwelker , Lab 06 instruction have been changed. Can you check ?

**Comment by mtwelker** [comment]
I'm glad I asked!  That new assignment makes much more sense.  Thank you, @Rami-Assaad !

**Comment by Johaning** [comment]
Thank you for asking and the answer! I had started working on the other instructions!

**Comment by lecy** [comment]
Thank you for the patience. I have been made aware that some people have not taken CPP 529 yet and thus that lab would have been challenging. 

I have made a bit of a switch so you can get more practice on the things that matter most. You get two new projects, hot off the press: 

https://watts-college.github.io/cpp-527-fall-2021/labs/lab-06-instructions/

https://watts-college.github.io/cpp-527-fall-2021/labs/final-project-instructions.html

I will send a note out via Canvas tonight with some schedule updates to make sure everyone has time. I'm going to let you pick between the code through and Lab 6 (I recommend Lab 6 unless you have already completed the code-through). 

The lab deadline has also been extended to Friday. 

There is not a lot of new content in both Lab 6 and the Final Project. It is mostly applications of things that we have covered already. I have provided you a lot of starter code because I want you to focus on the big picture of how all of the pieces fit together and not get stuck in the weeds of a specific step. 

I am hoping that these projects will help show how far you have come this semester and how you can start to put a lot of different tools together to do substantive analysis or reporting with the skills you now have (once you can consolidate knowledge from this semester).

**Comment by mtwelker** [comment]
Thank you for that information, Prof. @lecy !  
There's nothing new on Canvas yet, so students who haven't checked here may not know the assignments have changed.
