### ISSUE TITLE
Lab06 + Final Project 

### ISSUE THREAD

**Issue by AhmedRashwanASU** [Watts-College/cpp-527-fall-2021#47]
@lecy Good day Prof, please note that I was working on lab 6 and the final project for the past week, and submitted the same yesterday, however, found both of the projects are changed or not sure if there are some issues on the Syllabus page, could you please confirm.

**Comment by lecy** [comment]
Hi Ahmed - I did make some changes which hopefully make these final two assignments a little easier. 

The project that served as the final project last semester has become Lab 6: 

https://watts-college.github.io/cpp-527-fall-2021/labs/lab-06-instructions/

And a new final project was added: 

https://watts-college.github.io/cpp-527-fall-2021/labs/final-project-instructions.html

The dorling cartogram lab was a lot harder than either of these, but if you have started it and would prefer to complete that project I would allow you to submit it as a substitute for the new Final Project. 

https://watts-college.github.io/cpp-527-fall-2021/labs/dorling-lab/

Sorry to move things around! It is an improvement in content (the new labs are much better) and hopefully is not causing you a headache. I have dropped an assignment and extended deadlines to accommodate for the last-minute changes, but let me know if you run into any issues or if you want to substitute an assignment. 

I'm going on leave next term so I have been trying to update the course shell so it's ready to hand off to a new instructor, but creating new content is always more time intensive than you expect!

**Comment by AhmedRashwanASU** [comment]
@lecy, I did start and submit the Dorling Lab yesterday  , as well as the Final CV , however I will do my best to work on Lab 6 Part 1 and Final Lab in order to gather more content , the course is just perfect to be honest , we have accomplished many tasks which made a lot of sense to this program , Thanks Prof !

**Comment by lecy** [comment]
If you finished the CV lab already you are doing well. 

You can see that I added one step in the CV lab to create your own template function in R so you get a sense of what that process looks like, and also how you can borrow existing HTML templates to improve the look of reports once you understand how to integrate data from R with HTML tags.  

https://watts-college.github.io/cpp-527-fall-2021/labs/lab-06-instructions/#part-i---custom-reporting-functions

Regarding the dorling lab, if you completed that I will definitely accept it in lieu of the final project because it was not an easy lab. Just let me know if you are running into time constraints.
